name: Build, Lint, Test, Scan, and Deploy Node.js app to Azure Web App - LABUNACHAT

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build the project (if applicable)
        run: npm run build --if-present

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/proyecto-unachat:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/proyecto-unachat:latest

  lint:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Grant execute permission for ESLint
        run: chmod +x ./node_modules/.bin/eslint

      - name: Run ESLint
        run: npm run lint -- --fix

  test:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Grant execute permission for Mocha
        run: chmod +x ./node_modules/.bin/mocha

      - name: Run tests
        run: npm test

  scan:
      runs-on: ubuntu-latest
      needs: test
      steps:
        - uses: actions/checkout@v4
        
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
          
        - name: Log in to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        
        - name: Pull Docker image
          run: docker pull ${{ secrets.DOCKER_USERNAME }}/proyecto-unachat:latest
        
        - name: Run Trivy vulnerability scanner
          uses: aquasecurity/trivy-action@master
          with:
            image-ref: '${{ secrets.DOCKER_USERNAME }}/proyecto-unachat:latest'
            format: 'table'
            exit-code: '1'
            ignore-unfixed: true
            vuln-type: 'os,library'
            severity: 'CRITICAL,HIGH'

  deploy:
    runs-on: ubuntu-latest
    needs: test
    environment:
      name: 'Production'
    permissions:
      id-token: write

    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F9F8CBB729C242BBAF276EEC9F841F32 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F80FC5E87EA347F287FD3BD2FD90DE8C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BFFD7CB3E71940558F4B7EFABC230DBC }}

      - name: Deploy Docker image to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ProyectoUNACHAT'
          images: '${{ secrets.DOCKER_USERNAME }}/proyecto-unachat:latest'
