name: Nuclei Security Scan

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Set up Nuclei
      - name: Set up Nuclei
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://github.com/projectdiscovery/nuclei/releases/download/v3.3.5/nuclei_3.3.5_linux_amd64.zip
          unzip nuclei_3.3.5_linux_amd64.zip
          sudo mv nuclei /usr/local/bin/
          nuclei -version  # Verifica la instalación

      # 3. Download Nuclei templates
      - name: Download Nuclei Templates
        run: |
          git clone https://github.com/projectdiscovery/nuclei-templates.git ./nuclei-templates

      # 4. List downloaded templates (for debugging)
      - name: List downloaded templates
        run: |
          ls -l ./nuclei-templates

      # 5. Run Nuclei scan
      - name: Run Nuclei Scan
        run: |
          TARGET_URL=http://proyectounachat-awd3agg3fcckedc9.canadacentral-01.azurewebsites.net
          nuclei -u $TARGET_URL -t ./nuclei-templates -o nuclei-report.txt

      # 6. Upload report as artifact
      - name: Upload Report
        uses: actions/upload-artifact@v3
        with:
          name: nuclei-scan-report
          path: nuclei-report.txt
