on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Nuclei
        run: |
          curl -sSfL https://github.com/projectdiscovery/nuclei/releases/download/v2.9.5/nuclei_2.9.5_linux_amd64.zip -o nuclei.zip
          unzip nuclei.zip -d /usr/local/bin/
          chmod +x /usr/local/bin/nuclei
          nuclei -version

      - name: Verify Nuclei Installation
        run: |
          if ! [ -x "$(command -v nuclei)" ]; then
            echo "Nuclei installation failed!" >&2
            exit 1
          fi

      - name: Download Nuclei Templates
        run: nuclei -ut -ud /usr/local/nuclei-templates

      - name: Run Nuclei Scan
        run: |
          TARGET_URL=http://proyectounachat-awd3agg3fcckedc9.canadacentral-01.azurewebsites.net
          nuclei -u $TARGET_URL -t /usr/local/nuclei-templates -o nuclei-report.txt

      - name: Upload Report
        uses: actions/upload-artifact@v3
        with:
          name: nuclei-scan-report
          path: nuclei-report.txt
