name: Update SBOM

on:
  push:
    branches:
      - master  
  pull_request:
    branches:
      - master

jobs:
  generate-sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Install sbom-tool
        run: |
          wget https://github.com/microsoft/sbom-tool/releases/download/v3.0.0/sbom-tool-linux-x64 -O sbom-tool
          chmod +x sbom-tool
          sudo mv sbom-tool /usr/local/bin/

      - name: Generate SBOM
        run: sbom-tool generate -b . -bc ./ -pn "LabUNACHAT" -pv "1.0" -ps "ProjectScope"

      - name: Rename SBOM file
        run: |
          mv _manifest/spdx.json sbom.json

      - name: Commit and push updated SBOM
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add sbom.json
          git commit -m "Auto-update SBOM" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
